### ISSUE TITLE
不能工作

### ISSUE THREAD

**Issue by cline-tang** [chung-leong/conradish-x#194]
在电脑上的edge鼠标右击没有选项，点击工具栏里的扩展只有一个灰色而无法点击的“创建打印版本”，扩展的功能楼选项可以进去。来到扩展界面会看到检查视图显示“服务工作进程（不工作）”，已经尝试过重启浏览器了，还是无效。

**Comment by chung-leong** [comment]
Sorry for the delay. I'll look into it. Did you select any text before clicking the button? It would be useful to know what page you're trying to capture.

**Comment by cline-tang** [comment]
@chung-leong I am glad to get your reply ! I have tried it  in your way and now I can make it valid on my laptop.However I can't still use it in kiwi browser on the Android system,below is my screen record, do I use it in a wrong way again ?[https://linksharing.samsungcloudcn.com/vu3f2H7vM90x](url)

**Comment by chung-leong** [comment]
The extension won't work in Kiwi, as that browser shows the pop-up menu in a separate tab. That clears the selection in the original tab.
